pkg/operator/k8s/resource_helm.go

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
**Problem:**
Manifest from the helm chart may be without a namespace.
**Solution:**
Get the namespace from the release.
#1151

fix: helm manifest may not include namespace

---

pkg/dao/types/crypto/field.go
pkg/dao/types/property/field.go
pkg/dao/types/property/helper.go
pkg/templates/terraform_test.go
pkg/templates/testdata/complex_variable/main.tf

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
**Problem:**
Cannot deploy a template that has a compatible variable type.
**Solution:**
Adjust the type conversion of the schema property to support the compatible type.
#1154

fix: cannot deploy old compatible configs

---

pkg/apis/environment/basic.go

**Problem:**
When Get/List environments, the connector project is missing. as a result, it fails when we PUT using the entity from GET response.
**Solution:**
Add missing fields.

fix: missing project in env connectors

---

pkg/apis/environment/extension.go
pkg/apis/environment/extension_view.go
pkg/apis/service/extension.go
pkg/apis/service/extension_view.go
pkg/apis/serviceresource/basic.go
pkg/dao/service_resource.go
pkg/kms/driver_k8s.go
pkg/operator/alibaba/operator.go
pkg/operator/aws/operator.go
pkg/operator/k8s/driver.go
pkg/operator/k8s/driver_test.go
pkg/operator/k8s/kubeendpoint/endpoints.go
pkg/operator/k8s/operator.go
pkg/operator/k8s/operator_exec.go
pkg/operator/k8s/operator_get_components.go
pkg/operator/k8s/operator_get_endpoints.go
pkg/operator/k8s/operator_get_status.go
pkg/operator/k8s/operator_label.go
pkg/operator/k8s/operator_log.go
pkg/operator/k8s/polymorphic/selectors.go
pkg/operator/k8s/resource.go
pkg/operator/types/types.go
pkg/operator/unknown/operator.go
pkg/operator/unreachable/operator.go
pkg/server/runner.go
pkg/serviceresources/graph.go
pkg/serviceresources/key.go

**Problem:**
The response of the service resources listing is slow with `withKeys` query parameter. If the connectors are disconnected, the situation will intensify.
**Solution:**
1. For an operator, initialize the required clients first, and change the content type of the k8s rest config.
2. Get the keys of resources in parallel.
#1189

refactor: speed up getting resource keys

---

pkg/apis/server.go
pkg/apis/server_test.go
pkg/server/runner.go
pkg/server/start_apis.go

**Problem:**
Unable to start the server with --bind-address="ipv6 address", as the string in the form of "ipv6:port" is invalid for net listening.
**Solution:**
Parse the given bind address, if the given address is a strict IPv6, we use "[ipv6]:port" format.
Allow user to pick dual-stack mode or single-stack mode now.
#1202

fix: support binding ipv6 address

---

pkg/catalog/catalog.go
pkg/templates/git.go
pkg/templates/template.go
pkg/templates/terraform.go
pkg/vcs/repo.go

**Problem:**
Icon for standalone template does not show, manually sync will not update icon. The reason is that using the nickname instead of repository name to fetch icon.
**Solution:**
When sync standalone template or catalog template, support fetch icon and description.
#1192

fix: icon for standalone template does not show

---

staging/utils/cache/memory.go

**Problem:**
Print too many `Entry not found` logs during cache deleting.
**Solution:**
Mute the error if the key is not found under the memory cache.
#1212

fix: verbosity of memory cache deletion not found

---

pkg/vcs/options/options.go

**Problem:**
Failed to sync github catalog, the reason is vcs client add empty bearer token when token equals to `""`
**Solution:**
return client wirth user agent when token is empty
#1224

fix: vsc client bad credential

---

pkg/scheduler/service/relationship_check_task.go

**Problem:**
ServiceRelationshipCheck task will trigger to deploy the service that is depended on other services
**Solution:**
Missing return false when dependency is not ready， fix check dependency status
#1232

fix: check dependency failed

---

pkg/dao/entx/extension/view/template/ent.tmpl
pkg/dao/model/catalog_view.go
pkg/dao/model/connector_view.go
pkg/dao/model/environment_view.go
pkg/dao/model/perspective_view.go
pkg/dao/model/project_view.go
pkg/dao/model/service_view.go
pkg/dao/model/serviceresourcerelationship_view.go
pkg/dao/model/setting_view.go
pkg/dao/model/subject_view.go
pkg/dao/model/template_view.go
pkg/dao/model/templateversion_view.go
pkg/dao/model/variable_view.go

**Problem:**
The collection update validation doesn't work as expected introduced by https://github.com/seal-io/walrus/pull/1218, as there is a wrong indexing during refilling.
**Solution:**
Do indexing according to target elements.
#1190

fix: wrong collection validation of entx template

---

pkg/server/init_catalogs.go
pkg/settings/settings.go

**Problem:**
Make builtin catalog configurable, even though we can delete builtin catalog. When walrus restart the service, it will auto create a builtin catalog again.
**Solution:**
Add setting to enable or disable builtin catalog.
#1196

feat: add enable builtin catalog setting

---

pkg/apis/subject/basic.go
staging/utils/errorx/error.go

**Problem:**
HTTP error message have status fields.
```
{
"message": "400 Bad Request: error setting password: dial tcp4 127.0.0.1:8000: connect: connection refused",
"status": 400,
"statusText": "Bad Request"
}
```
**Solution:**
Remove it when formatting.
https://github.com/seal-io/walrus/issues/744

fix: http error message have status fields

---

pkg/apis/cost/validation/query.go
pkg/costs/deployer/template.go
pkg/costs/syncer/k8s.go

**Problem:**
1. Opencost opens a lot of connections to prometheus, after the request is finished, a bunch of connections are still in TIME_WAIT status, which makes can't open connections to prometheus.
2. Missing empty check for share cost causes validate crash
**Solution:**
1. Adding opencost query concurrency
2. Adding empty share cost query
#1038 
#1222

fix: add max query concurrency to open cost and fix validate bugs

---

pkg/k8sctrls/manager.go
pkg/k8sctrls/setup.go
pkg/kms/driver_k8s.go
pkg/server/init.go
pkg/server/init_health_checkers.go
pkg/server/runner.go
pkg/server/start_k8sctrls.go

**Problem:**
Too many service creations will make the Kubernetes cluster inaccessible for a while, and then the inside controller manager will quit as failed to renew its leadership.
**Solution:**
- Support customizing the leader election lease duration and renewing timeout.
- Do not shut down immediately when lost leader election, instead, retry for some time.
#1096

fix: shutdown when leader election lost

---

pkg/deployer/terraform/deployer.go

**Problem:**
After creating a new service, the status->summaryStatus of the service revision  is empty.
**Solution:**
Set summary before creating service revision.
https://github.com/seal-io/walrus/issues/1225

fix: the summary status of service revision is empty after creating.

---

pkg/apis/serviceresource/extension.go
pkg/apis/serviceresource/helper.go

**Problem:**
Close the resize channel before processing the resize read, which often, happens on `shell` negotiate phase.
**Solution:**
- Do not close the resize channel and rely on the go runtime GC.
- Always send `exit` in case of session leaking.
- Modify the return error from Terminal `Read` to reduce below tedious logs.
```
E       websocket: close 1005 (no status)
E       websocket: close 1001 (going away)
E       read [::443] -> [::xxx] use of closed network connection
```
#1257

fix: failed connect resource terminal

---

pkg/catalog/catalog.go
pkg/scheduler/catalog/template_sync_task.go
pkg/settings/modifier.go
pkg/settings/settings.go
pkg/templates/git.go
pkg/templates/terraform.go
pkg/vcs/repo.go
staging/utils/cron/cron.go

**Problem:**
- Sync an template with tags more than 100 may take more than 5 min to update template version, remove timeout.
- The logs of sync an catalog are too brief, it is hard to monitor the progress of sync an catalog.
The reason is the cron task will set timeout with previous task time. While syncing catalog, the timeout limit will be longer than the calculation after setting a short crontab expression, it may lead to timeout.
**Solution:**
- Remove timeout of sync template.
- Add debug logs of sync an catalog.
- Use a longer task timeout, using a new context to update catalog status.
#1048

fix(catalog): remove timeout and add logs

---

pkg/templates/git.go

**Problem:**
Get wrong icon URL
**Solution:**
Fix icon get URL of self-host github
#1268

fix:  get wrong icon address

---

deploy/manifests/kubernetes.yaml
pkg/dao/types/built_in_names.go
pkg/server/init_deployer_runtime.go

**Problem:**
cannot create internal k8s resources in HA mode after https://github.com/seal-io/walrus/pull/1278 merged.
**Solution:**
- Remove mounting the walrus SA for deployment runner.
- Allow walrus consuming SAR to check the authorization.
@Finenyaco , need to use the new `kubernetes.yaml` to deploy.
#1282

fix: failed install on HA mode

---

pkg/dao/types/property/field.go

**Problem:**
When an error occurs during variable parsing, the error message lacks the specific failed variable which makes it hard to diagnose for templates with a large number of variables, like `https://github.com/terraform-google-modules/terraform-google-kubernetes-engine`.
**Solution:**
Added corresponding variable name to the variable validation's error message.
#1227

feat: add variable name to validation error message

---

pkg/apis/environment/basic.go
pkg/apis/environment/basic_view.go
pkg/apis/environment/common.go
pkg/apis/environment/extension.go
pkg/apis/environment/extension_view.go

**Problem:**
The original API used for cloning environment is the same as creating environment, which cannot handle the case of cloning sensitive variables.
**Solution:**
Add a specific clone environment API to decouple with the creation API, which queries and fills in the value of sensitive variables.
#985

feat: add clone environment api

---

pkg/apis/template/basic.go
pkg/apis/template/basic_view.go

**Problem:**
When catalog templates and non-catalog templates are mixed together, it's difficult to find the non-catalog templates. 
**Solution:**
Since not providing `catalogId` is already used for querying all templates, add a `nonCatalog` param to fetch non-catalog templates only.
#1193

feat: support non-catalog template filter

---

pkg/templates/git.go

**Problem:**
The hash reference of the tag sometimes points to the tag itself, instead of the commit. 
**Solution:**
Obtain an `*object.Tag`, then find the target commit in the Target field.
#1297

fix: failed to reset to tag when syncing templates

---

pkg/dao/types/property/field.go
pkg/dao/types/property/field_test.go

**Problem:**
When the property type is a nested compound type, it fails to validate elements with type `any`.
**Solution:**
Use the builtin function of go-cty to check dynamic types recursively.
#1302

fix: failed to validate (any) elements nested in compound types

---

go.mod
go.sum
pkg/catalog/catalog.go
pkg/catalog/catalog_test.go
pkg/deployer/terraform/deployer.go
pkg/settings/settings.go
pkg/templates/git.go
pkg/vcs/repo.go

**Problem:**
Self-signed certificates is not supported in both catalog fetching and terraform deploying.
**Solution:**
- Support configuring skip SSL certificates verification in global settings `SSLSkipVerify`.
- Config InsecureSkipVerify to the `http.Client` fetches catalogs if `SSLSkipVerify` is set.
- Set `GIT_SSL_NO_VERIFY` environment variable for local template cloning and service deploying job if `SSLSkipVerify` is set.
#1296

fix: self-signed certificates catalog not supported

---

pkg/apis/environment/extension.go
pkg/dao/types/graph.go

**Problem:**
The service icons show in dependency graph are always the default icon.
**Solution:**
Support service customized icon by using the corresponding template icon.
#965

feat: return template icons in dependency graph response

---

pkg/dao/types/template_version.go

**Problem:**
OpenAPI info version is useless and confusing.
**Solution:**
Not require the version and skip validate it while user customizes the UI schema
#1306

refactor: ignore openapi info version validate

---

pkg/apis/resourcedefinition/basic.go
pkg/templates/openapi/operation.go

**Problem:**
When creating a def with multiple matching rules, it panic on marshalling the output.

fix: marshaling resource definition output panic

---

pkg/deployer/terraform/deployer.go

**Problem:**
Labels are missing so the matching is unexpected.
https://github.com/seal-io/walrus/issues/1408

fix: select resource labels for matching rules

---

pkg/deployer/terraform/deployer.go

**Problem:**
resource attributes are overrided by attributes in matching rules.
**Solution:**
Switch precedence.
https://github.com/seal-io/walrus/issues/1398

Change resource attr precedence

---

pkg/apis/environment/extension.go
pkg/deployer/terraform/deployer.go
pkg/deployer/terraform/parse.go
pkg/deployer/terraform/parse_test.go
pkg/resource/resource.go
pkg/terraform/config/config.go
pkg/terraform/config/types.go

Problem:
Reference in ${resource.name.output_name} format does not work.
Solution:
Update parsing to make it work. Also support using ${service.name.output_name} for resource of service type.
https://github.com/seal-io/walrus/issues/1407

fix: reference service & resource outputs

---

pkg/apis/template/basic_view.go
pkg/templates/constraint.go
pkg/templates/git.go
pkg/vcs/repo.go

**Problem:**
Can not import subdirectory template from remote repository.
**Solution:**
Support subdirectory template import.
Example:
`https://github.com/alexcodelf/webservice//sub`
`https://github.com/alexcodelf/webservice//sub?ref=main`
The subdirectory is following double slashes.
#template
#1339

feat: support subpath module import

---

pkg/apis/resourcerevision/extension.go

**Problem:**
When redeploying previously failed service, new instance dependencies are created before the instances are created, so the id field is blank, causing deployment fail.
**Solution:**
Save the new instances first before update dependencies.
#1435 
#1351

fix: failure to upgrade service when first deployment fails

---

pkg/deployer/terraform/deployer.go
pkg/resource/resource.go

**Problem:**
Now deletion is done by completion of a revision. It's not feasible for a resouce failing to match a definition. It cannot build a revision whose templateID is required.
**Solution:**
Do straight deletion instead of creating a revision and delete via revision status sync if nothing needs to be destroyed.
https://github.com/seal-io/walrus/issues/1442

refactor: do straight deletion when no components exist

---

pkg/templates/git.go

**Problem:**
When project_id is nil, the sql query fails to parse this field.
**Solution:**
Add the condition ProjectIDIsNil.
#1451

fix: error adding a template when the template repo has no tags

---

pkg/apis/perspective/extension.go

**Problem:**
Connectors of non-Kubernetes type were shown in the perspective select list
**Solution:**
Should not show non-Kubernetes type connector in perspective select list
#1456

fix: connectors of non-Kubernetes type were shown in perspective select list

---

pkg/templates/loader/terraform_loader.go
pkg/templates/loader/terraform_loader_test.go
pkg/templates/translator/terraform_translator.go
pkg/templates/translator/translator.go
pkg/terraform/parser/parser.go

**Problem:**
While generating schema from variables.tf, can't support generating the order of object's properties
**Solution:**
Support generating object properties's order
#1306

refactor: support generate order of terraform object

---

.github/workflows/ci.yml

**Problem:**
Walrus CLI can only download from walrus server
**Solution:**
Release walrus CLI in github repo asset
#1486

refactor: release walrus CLI in github repo asset

---

pkg/cli/schema/format.go
pkg/dao/types/schema.go
pkg/templates/loader/terraform_loader.go
pkg/templates/loader/terraform_loader_test.go
pkg/templates/openapi/ext.go

**Problem:**
1. The template without variable will crash
2. while calling of schema expose function will reset the schema
3. add group order while generating
**Issue**
#1518
#1517

fix: prevent crash while no variable and add generate groupOrder

---

.github/workflows/mirror_images.yml

**Problem:**
without new line the last image can not be mirrored
**Solution:**
Add condition `[[ -n "$line" ]]` checks if the $line variable is non-empty after the read command fails to read a new line.

fix: mirror image

---

pkg/templates/loader/terraform_loader.go

**Problem:**
Server will set the default order and colSpan
**Solution:**
Should not set default order and colSpan while existed
#1485

refactor: don't set order and colspan while schema.yaml existed

---

pkg/apis/environment/extension.go

**Problem:**
Always reutrns all resource definitions for an environment regardless of the selectors because selector is not queried before the matching.
https://github.com/seal-io/walrus/issues/1580

fix: add missing selector in matching rule query

---

pkg/workflow/deployer/default.go

**Problem:**
Workflow server image pull policy is `Always`, offline still pull image.
**Solution:**
Change workflow deployer image pull policy to `IfNotPresent` for airgap

fix: offline prevent server start

---

pkg/apis/runtime/scheme_route.go

**Problem:**
View some of the API in openAPI swagger return error could not found schema
**Solution:**
reset the `visited` to prevent get doesn't exit schema
#1623

fix: still generate schema for object without properties

---

pkg/vcs/repo.go

**Problem:**
When the walrus can't access GitHub, syncing the catalog will create a lot of Git processes and get stuck.
**Solution:**
Add timeout for context.
#1622

fix: add timeout to clone repo

---

pkg/operator/k8s/kubestatus/walker.go

**Problem:**
When a container service include init container, initialized is false before the init container completed.
**Solution:**
Change the display status to `Initializing` when reason is `ContainersNotInitialized`.
#1625

fix: display initializeFailed when the pod is initializing

---

deploy/manifests/kubernetes.yaml
pkg/apis/project/handler.go
pkg/apis/setup.go
pkg/apis/workflow/handler.go
pkg/apis/workflowexecution/handler.go
pkg/apis/workflowstageexecution/handler.go
pkg/apis/workflowstepexecution/handler.go
pkg/costs/deployer/cost_tools.go
pkg/costs/deployer/default_test.go
pkg/k8s/deploy/deployer.go
pkg/k8s/deploy/helm.go
pkg/k8s/helper.go
pkg/k8sctrls/setup.go
pkg/workflow/client.go
pkg/workflow/deployer/default.go

**Problem:**
Walrus crashed and restarted because argo workflows failed to install.
**Solution:**
Add permission for apply walrus in k8s, using `rest.Config` directly instead of converting to`clientcmdapi.Config`
#1644

fix: argo workflows failed to install

---

cmd/server/server.go

**Problem:**
further fix after PR https://github.com/seal-io/walrus/pull/1679 to avoid ISSUE #1678 and address ISSUE #1622.
**Solution:**
reap child processes if run as PID 1.
https://github.com/seal-io/walrus/issues/1622

refactor: reap child processes if run as pid 1

---

pkg/operator/k8s/kubestatus/walker.go

**Problem:**
When the pod has no condition yet, the default summary status uses the last step in the path, which is `DisruptionTarget` in this case.
**Solution:**
Move `DisruptionTarget` to be in front of `Ready`.
#1692

fix: displays Evicting status while no summary

---

pkg/catalog/catalog.go
pkg/vcs/repo.go

**Problem:**
Sometines catalog sync template will failed, the getter's context be replaced everytime will cause exit for cloning.
**Solution:**
New getter for each getter.

fix: sync catalog git clone failed

---

staging/utils/signals/handler.go

- enlarge wait time to wait child process to call `syscall.Wait4` normally
**Problem:**
As #1706 reap zombie process, we sometimes still encounter `no child process` error for child process.
**Solution:**
Enlarge wait time to wait child process to call [syscall wait4](https://github.com/golang/go/blob/619b8fd7d2c94af12933f409e962b99aa9263555/src/os/exec_unix.go#L42-L47) and  reap zombie after that.
#1711

fix: reap child process before cmd wait finished

---

pkg/templates/constraint.go

**Problem:**
Panic occur when import invalid template. The reason that `main(dev)` version does not have this issue is we ignore walrus version contraint check in `main(dev)` version.
**Solution:**
Check variable before get schema ext walrus version
#1693

fix: check template constraint nil error

---

pkg/apis/environment/extension.go
pkg/resourcedefinitions/match.go
pkg/resourcedefinitions/match_test.go

**Problem:**
When finding available resource types for an environment, it compares with empty resource label so it never match if there's resource label selector.
**Solution:**
Ignore resource label selector in environment level matching.
https://github.com/seal-io/walrus/issues/1719

fix: available resource types for envs

---

cmd/cli/command.go
hack/lib/style.sh

refactor linting steps.
- replace `goimports` with `goimports-reviser`, a better import grouping solution.
- remove the single `gofumpt` formatting logic, as the `golines` does that again with its `--base-formatter`.
- fix the ignored directories arguments of `golines`, use `--ignored-dirs=.git --ignored-dirs=node_modules --ignored-dirs=vendor` instead of `--ignored-dirs=".git node_modules vendor"`.

chore: lint

---

pkg/apis/setup.go
pkg/server/runner.go
pkg/server/start_apis.go

**Problem:**
The maximum number of websocket connections is fixed. Only 10 terminals can be connected at the same time with one source ip.
**Solution:**
Support for configuring the maximum number of websocket connections by startup command flag.
#1431

feat: support configuring max websocket connections

---

pkg/dao/types/workflow.go
pkg/workflow/step/service_step.go

**Problem:**
- workflow can define duplicate variables
- service create duplicated when retry times over 1. 
The reason is we have already defined step type to `create`, when create a new servcie failed in step, it actually create a new service, but retry in step will not change jobType dynamically. In this case, step will use `create` API to interact with server will return error 409.
**Solution:**
- add variable validation for workflow create or update
- get service step type with in step, if servcie is created then try to upgrade service in servcie step.
#1676 #1520

fix: workflow issues

---

pkg/apis/environment/basic_view.go
pkg/dao/types/status/status.go
pkg/dao/types/status/status_resource.go
pkg/dao/types/status/status_resourcerevision.go
pkg/dao/types/status/walker.go
pkg/dao/types/status/walker_test.go
pkg/operator/k8s/kubestatus/walker.go

**Problem:**
Resource API cannot differentiate inactive status from active status.
**Solution:**
Add an `InActive` field to status summary and update it in WalkResource.
#1500

feat: Classify inactive status in resource API

---

pkg/apis/catalog/basic.go
pkg/apis/connector/basic.go
pkg/apis/environment/basic.go
pkg/apis/resource/basic.go
pkg/apis/resource/extension.go
pkg/apis/resourcecomponent/basic.go
pkg/apis/resourcedefinition/basic.go
pkg/apis/resourcedefinition/extension.go
pkg/apis/resourcerevision/basic.go
pkg/apis/template/basic.go
pkg/apis/workflow/basic.go
pkg/apis/workflowexecution/basic.go
pkg/apis/workflowstepexecution/extension.go
pkg/dao/migration/trigger_modelchange.go
pkg/datalisten/modelchange/dispatch.go
pkg/datalisten/modelchange/event.go
pkg/datalisten/modelchange/event_buffer.go
pkg/workflow/status.go

**Problem:**
The database record has already been removed when a resource deletion notified, so it cannot locate the corresponding environment to notify statistics update.
**Solution:**
Add common foreign keys(`environment_id`, `project_id`) to database change trigger notification. Directly use this id retrieved from the old table instead of querying after deletion.
#1454

fix: service deletion not update on environment list

---

pkg/apis/resource/basic_view.go
pkg/dao/resource_relationship.go
pkg/deployer/terraform/deployer.go
pkg/deployer/terraform/parse.go
pkg/deployer/terraform/parse_test.go
pkg/resource/topology_test.go

- support variable reference in array
- short resource reference
**Problem:**
- Can not parse variables and resource reference in array.
- Normal shell variable like `${MYSQL_HOST}` in attribute will make deployment failed.
- Reference of `resource` or `service` make it inconvenient to use.
**Solution:**
- Support parse reference in array of attributes.
- Auto convert to [escape-sequences](https://developer.hashicorp.com/terraform/language/expressions/strings#escape-sequences-1) from `${` to `$${`  if attributes contains `${` that is not walrus variables. ~~User may manually use `$${MYSQL_HOST}` directly if they want, parser will keep it if found double dollar of sequence.~~
- Use short reference `svc` and `res`, now we can use `${svc.service1.output}` and `${res.resource1.output}`
@hibig …

refactor: modify resource reference parser

---

pkg/apis/resource/basic.go
pkg/resource/topology.go

**Problem:**
Failed to batch delete resource with dependecies with no components.  Walrus will delete resource directly if it has no components, dependency check will be skipped.
**Solution:**
Reverse topology sort before delete resources, when resources does not have components. 
#1636

fix: failed delete resources with dependencies

---

pkg/apis/templateversion/extension.go
pkg/bus/setup.go
pkg/bus/templateversion/bus.go
pkg/cli/schema/generate.go
pkg/dao/types/schema.go
pkg/deployer/terraform/context.go
pkg/templates/constraint.go
pkg/templates/git.go
pkg/templates/openapi/ext.go
pkg/templates/syncer.go

**Problem:**
UI schema should not show context. Walrus will auto inject context when deploying, user does not care about this field.
**Solution:**
Since we need keep it in schema of the template to determine whether inject walrus context to the template. **The proposed solution involves excluding the context field when generating the UI schema file for the template. If users wish to modify the UI schema in Walrus, the context field will not be hidden, allowing for customization.**
#1528

fix: hidden context variable in UI schema

---

pkg/apis/resourcecomponent/extension.go
pkg/apis/resourcerevision/extension.go
pkg/connectors/status.go
pkg/dao/types/built_in_labels.go
pkg/operator/k8s/kubeendpoint/endpoints.go
pkg/operator/k8s/operator.go
pkg/operator/k8s/operator_get_endpoints.go
pkg/operator/types/new.go
pkg/resourcecomponents/key.go
pkg/scheduler/resourcecomponent/helper.go
pkg/server/init.go
pkg/server/init_local_environment.go
pkg/settings/settings.go

Add a new setting `LocalEnvironmentMode`. Available options include `kubernetes` and `disabled`. It can be extended with `docker` in further enhancements.
Support fetching proxy endpoints for resources when a dedicated connector label is present. It helps to access deployed services without port forwarding in standalone setup.
Related issue:
https://github.com/seal-io/walrus/issues/1203

feat: add local environment

---

go.mod
go.sum
pkg/catalog/catalog.go
pkg/dao/types/git.go
pkg/server/init.go
pkg/server/init_catalogs.go
pkg/server/runner.go
pkg/templates/git.go
pkg/vcs/client.go
pkg/vcs/driver/gitee/gitee.go

**Problem:**
Template Catalog is not supported.
**Solution:**
Add gitee client to support gitee catalog. This is partial Pull Request to address #1736 we need support catalog server mirror [walrus-catalog](https://github.com/walrus-catalog) to gitee.
**Additional**
cc @hibig UI need a new catalog type `Gitee`, one thing to note is that template icons cannot be displayed from gitee, as gitee has implemented measures to prevent hot-linking of images, all image link will return 403. The possible measure is to set `<meta name="referrer" content="no-referrer">`
#1736

feat: support gitee catalog

---

pkg/dao/types/built_in_labels.go
pkg/k8s/local.go
pkg/operator/k8s/kubeendpoint/endpoints.go
pkg/operator/k8s/operator.go
pkg/operator/k8s/operator_get_endpoints.go
pkg/server/init_local_environment.go

**Problem:**
Current proxy implementation does not work if the exposed service requires accessing the root path.
**Solution:**
Use node port to expose embedded services like normal clusters.
Some adaptations for the embeded cluster:
- Shrink node port range of embedded k3s to avoid long bootstrap time.
- Use hostname of walrus server instead of the discovered node IP because it's not accessbile externally.
To make it work, users need to start walrus with additional port mappings:
$ docker run -d -p 80:80 -p 443:443 **-p 30000-30100:30000-30100** --privileged sealio/walrus
Reasons not using host network:
1. Occupied ports are not clear.
2. It can easily conflicts with ports from other services. For example when developing walrus with a local k8s. …

refactor: use nodeport to expose services in embedded cluster

---

pkg/apis/environment/common.go
pkg/apis/resource/basic.go
pkg/apis/resource/extension.go
pkg/apis/resource/extension_view.go
pkg/resource/resource.go

**Problem:**
At this stage, there is no redeployment of operations. Each deployment requires editing and then upgrading, which is very inconvenient for users. Moreover, walrus does not support batch start and stop resources.
**Solution:**
- add reapply/batch reapply APIs
- add batch stop/start APIs
- set resource label stoppable in dev and staging by default.
#1463 #1765

feat: support batch resource operations

---

pkg/apis/workflowexecution/extension.go
pkg/dao/types/status/status_workflow_execution.go
pkg/dao/types/status/walker.go
pkg/workflow/client.go
pkg/workflow/reconcile.go
pkg/workflow/status.go

**Problem:**
- manual delete workflow from k8s will make workflow status stuck.
- after stopping the workflow, the workflow status will change to "Failed"
**Solution:**
- When terminate or resume workflow, check workflow exist in cluster, if not mark workflow status to failed.
- add status `Canceled`
#1523
@hibig UI need adjust status of workflow.

fix: workflow status 

---

pkg/cli/config/cache.go

**Problem:**
CLI may crash when generate schema in CI
**Solution:**
Should not return nil when file is not existed
**Issue:**
https://github.com/seal-io/walrus/issues/1800

fix: cli may crash when generate schema in ci

---

pkg/templates/constraint.go

**Problem:**
Deploy resource to wrong namespace.
**Solution:**
The reason is that fetching origin schema with wrong method.
#1803

fix: get wrong schema for template version

---

pkg/apis/runtime/scheme_route_extension.go
pkg/cli/manifest/request.go

**Problem:**
Used to lock collection post request to batch-create and batch-delete, it causes problem since this PR https://github.com/seal-io/walrus/pull/1743 add more batch post operation
**Solution:**
Generate operation name based on go func
#1797

fix: should not lock operation name since we may add new batch operation

---

pkg/dao/environment.go

**Problem:**
Can not update environment when labels is empty of the environment.
**Solution:**
Init labels when environment labels is nil
#1806

fix: enviornment update failed

---

deploy/manifests/kubernetes.yaml
pkg/server/init_local_environment.go

**Problem:**
1. Fail to get kubeconfig for local cluster when running in cluster.
2. Lacking permissions to install hermitcrab/argo workflows & deploy walrus resources.
**Solution:**
generate kubeconfig when running in cluster.
Update walrus role so that it can deploy basically anything on local cluster.
https://github.com/seal-io/walrus/issues/1798

fix: missing kubeconfig/permission for local cluster in HA

---

pkg/templates/loader/testdata/any_variable/expected.yaml
pkg/templates/loader/testdata/complex_variable/expected.yaml
pkg/templates/loader/testdata/full_schema/expected.yaml
pkg/templates/loader/testdata/with_output/expected.yaml
pkg/templates/openapi/ext.go
pkg/templates/translator/terraform_translator.go
pkg/templates/translator/translator.go

**Problem:**
Variable including any type will generate any type schema, this may cause loss of the original type info.
**Solution:**
Refactor generate schema of any type, add widget: YamlEditor for any type 
#1833

refactor: generate schema which sub schema include any type

---

pkg/templates/git.go
pkg/templates/loader/loader.go
pkg/templates/loader/terraform_loader.go
pkg/templates/loader/terraform_loader_test.go

**Problem:**
UI schema should generate from schema.yaml when exists but doesn't fully implement
**Solution:**
UI schema should use schema from schema.yaml when exists.
#1833

refactor: ui schema should use schema.yaml while it exsited

---

pkg/templates/constraint.go
pkg/templates/git.go

**Problem:**
Sync from the catalog still shows widget YamlEditor for variable: containers in https://github.com/walrus-catalog/terraform-kubernetes-containerservice 
**Solution:**
Should use schema in schema.yaml while exist
#1833

fix: should use schema.yaml while exist in sync catalog

---

cmd/cli/command.go
pkg/apis/runtime/openapi/extension.go
pkg/apis/runtime/scheme_route.go
pkg/cli/api/api.go
pkg/cli/api/cache.go
pkg/cli/api/openapi.go
pkg/cli/api/operation.go
pkg/cli/api/version.go
pkg/cli/cmd/apply.go
pkg/cli/cmd/context.go
pkg/cli/cmd/delete.go
pkg/cli/cmd/local.go
pkg/cli/cmd/login.go
pkg/cli/cmd/prerun.go
pkg/cli/cmd/schema.go
pkg/cli/cmd/version.go
pkg/cli/common/error.go
pkg/cli/common/http_status.go
pkg/cli/config/cache.go
pkg/cli/config/config.go
pkg/cli/manifest/operator.go
pkg/cli/manifest/request.go
staging/utils/version/version.go

**Problem:**
1. cli command config is not clear enough
2. environment start/stop lack of arg
**Solution:**
1. use login and context to replace config
2. environment start/stop lack of arg
#1790 
#1761

refactor: replace config command with login and context

---

pkg/apis/environment/extension.go

**Problem:**
Stoppable is environment-independent
**Solution:**
Remove stoppable while export walrus file
#1814

refactor: remove stoppable while export walrus file

---

pkg/cli/cmd/context.go

**Problem:**
Inconvenient while switching context, better print the current context
**Solution:**
Print the current context after switch
#1782

refactor: print current context after switch

---

staging/utils/cron/cron.go

when analyzing #1319, a mistake in cron scheduler use was found. 
this PR configures the distribution lock before starting the scheduler.
it's noted that this PR doesn't address https://github.com/seal-io/walrus/issues/1319 as fewer clues were provided as I mentioned: https://github.com/seal-io/walrus/issues/1319#issuecomment-1888600304.

fix(cron): configure locker after start scheduler

---

pkg/resourcedefinitions/builtin.go

**Problem:**
Rename resource type. e.g. builtin-mysql->mysql.
#1708

fix: rename resource type

---

hack/package.sh
pack/server/image/Dockerfile
pkg/apis/setup.go
pkg/apis/walrusfilehub/handler.go
pkg/settings/settings.go

Serve walrus file sample index, with the following changes:
- packages the hub repo under /var/lib/walrus/walrus-file-hub in server image.
- serves `/walrus-file-hub` API for the index and `/walrus-file-hub/*filepath` for static resources like icons.
https://github.com/seal-io/walrus/issues/1836

feat: add walrus file hub

---

pkg/apis/resource/basic_view.go
pkg/cli/cmd/delete.go
pkg/cli/common/http_status.go
pkg/cli/formatter/table.go
pkg/cli/manifest/operator.go

**Problem:**
1. Could apply walrus file without type and template config
2. Deleting resources that depended on others via the walrus file returns inaccurate error messages
**Solution:**
Add more validation and expose more accurate errors while apply/delete walrus file failed
#1768 
#1783

fix: expose error message while apply/delete walrus file failed

---

pkg/apis/resource/extension_view.go
pkg/dao/types/schema.go
pkg/templates/constraint.go
pkg/templates/git.go
pkg/templates/loader/terraform_loader.go
pkg/templates/loader/testdata/full_schema/expected.yaml

**Problem:**
1. context in the original schema has been removed while exposing ui schema which caused the failure to deploy
2. upgrade failed
**Solution:**
1. exposing ui schema should not affect the original schema
3. set environment ID while computing attributes in the upgrade
#1889 
#1890

fix: origin schema context had been removed while exposing ui schema

---

pkg/cli/local/install.go
pkg/server/init.go
pkg/server/init_docker_mode.go

**Problem:**
The host.docker.internal domain only works in particular docker descktop versions, making the deployment fails.
**Solution:**
Set ServeUrl setting by network interface IP in docker mode.
https://github.com/seal-io/walrus/issues/1710

fix: update ServeUrl in docker mode

---

go.mod
pkg/templates/openapi/default.go
pkg/templates/openapi/default_test.go
pkg/templates/openapi/stack.go
pkg/templates/openapi/testdata/list/expected.json
pkg/templates/openapi/testdata/map/expected.json
pkg/templates/openapi/testdata/object/expected.json
pkg/templates/openapi/testdata/object/main.tf
pkg/templates/openapi/testdata/object/schema.yaml
pkg/templates/openapi/testdata/simple/expected.json

**Problem:**
Now will generate below computed attributes cause terraform validate failed.
```json
{
"seeding": {
"type": "none",
"url": {
"storage": {
"size": 10240
}
}
}
}
```
**Solution:**
Update generate computed attributes strategy, only generate optional(fieldname, "default") while the object default existed.
After updated:
```json
{
"seeding": {
"type": "none"
}
}
```
#1900

fix: update generate default for schema

---

pkg/apis/resource/common.go
pkg/apis/resource/extension_view.go

**Problem:**
1. Batch resource deploying doesn't accept real input resources.
2. `ComputedAttributes` doesn't be provided for reusing deployment.
**Solution:**
1. Use request resources;
2. Select `ComputedAttributes`.
#1906

fix: failed on resource batch deploying

---

pkg/dao/types/status/status_workflow_execution.go

**Problem:**
Workflow execution status inactive shows wrong color in UI.
**Solution:**
Mark inactive for cancelled workflow execution.
#1840

fix: workflow execution cancelled status inactive

---

pkg/resourcedefinitions/helper.go
pkg/resourcedefinitions/testdata/shrink/given.1.yaml
pkg/resourcedefinitions/testdata/shrink/given.2.yaml
pkg/templates/schema_default.go

**Problem:**
the default value of the nested structure has been cleaned, for example, the default of `a.b.c` has been reset, however, `a.b` doesn't have a default.
**Solution:**
make sure not to reset the child's values if the parent is empty.
#1898

fix: remove nested default values

---

pkg/catalog/catalog.go
pkg/settings/settings.go

**Problem:**
Two separate settings to control disabling built-in catalog and resource definitions looks scattered.
**Solution:**
Remove the resource definition setting and use the existing builtin catalog one.
#1920

feat: unify settings for built-in catalog and definitions

---

pkg/cli/schema/format.go
pkg/templates/openapi/ext.go
pkg/templates/openapi/operation.go

**Problem:**
Template CI failed since cli generated schema.yaml removed groupOrder
https://github.com/walrus-catalog/terraform-kubernetes-mysql/actions/runs/7543284155/job/20533957739
**Solution:**
Fix cli-generated schema.yaml to get back missing groupOrder

fix: update cli generate schema to fix template ci

---

pkg/apis/resource/basic_view.go
pkg/apis/resource/extension_view.go

**Problem:**
env type selector is broken due to missing type in the query.
**Solution:**
Remove select.
https://github.com/seal-io/walrus/issues/1922

fix: remove env field select so that type is available for matches

---

pkg/dao/resource.go
pkg/resource/resource.go
pkg/scheduler/resource/relationship_check_task.go

**Problem:**
Stopping and starting the environment can result in resources being perpetually in the Progressing running status. 
B &rarr; A
In the event where Resource B is waiting for Resource A, both will be stuck in the progressing status — Resource A is in the process of stopping, while Resource B is in deployment. Consequently, they will end up waiting for each other indefinitely, causing a lock in their statuses.
**Solution:**
Check dependecies before progressingly apply resource, dependencies to be delete will make resource deploy failed.
Check dependant before stop/delete resource, dependants to be deployed will make stop/delete failed.
#1628

fix: resource stuck in progressing

---

pkg/templates/git.go

**Problem:**
Reset template version schema wrong. The reason is that git repo not reset to target version tag.
**Solution:**
Reset git repo to right version.
#1940

fix: template version schema reset wrong

---

pkg/apis/resourcerevision/extension.go
pkg/operator/k8s/operator.go
pkg/server/init_configs.go
pkg/server/init_local_environment.go
pkg/servervars/vars.go

as #1932 mentioned, we cannot access an endpoint with the internal k3s node IP(a.k.a. the walrus container's IP).
- get non-loopback IPs at the beginning
- replace the endpoint's host/IP with the server's host if it matches the above IP set.
#1932

feat: replace local ip endpoint with server's host

---

pkg/resource/computed_attributes.go

**Problem:**
lack of attributes causes apply walrus file failed
**Solution:**
check attributes empty before generate computed attributes
#1923

fix: empty attributes causes apply walrus file failed

---

pkg/apis/environment/extension.go

**Problem:**
Available defs of the environment exclude all definitions with resource label selectors.
**Solution:**
Strip resource level selectors when matching at environment level.
https://github.com/seal-io/walrus/issues/1945

fix: env/res-defs missing defs with resource label selector

---

pkg/deployer/terraform/syncer.go

**Problem:**
Deleting resource will stuck forever. When an resource is deleting, and create a resource depends on it, it will stuck when revision finished and failed to delete.
**Solution:**
If delete resource failed, try to get dependant infos and update resource.
#1953

fix: resource stuck in deleting

---

pkg/apis/catalog/basic_view.go
pkg/apis/connector/basic_view.go
pkg/apis/environment/basic_view.go
pkg/apis/environment/common.go
pkg/apis/perspective/basic_view.go
pkg/apis/project/basic_view.go
pkg/apis/resource/basic_view.go
pkg/apis/resourcedefinition/basic_view.go
pkg/apis/subject/basic_view.go
pkg/apis/variable/basic_view.go
pkg/apis/workflow/basic_view.go
pkg/auths/account_handler_view.go
staging/utils/validation/validation.go

**Problem:**
Walrus creates a Kubernetes namespace {projectName}-{environmentName} when environment created. The namespace should not be over 63 characters.
**Solution:**
Limit all object names within 30 characters, except for templates(considering lengthy ones like [terraform-aws-managed-service-prometheus](https://github.com/terraform-aws-modules/terraform-aws-managed-service-prometheus).
#1564

fix: can't create environment when the name length is 63

---

pkg/catalog/catalog.go
pkg/resourcedefinitions/builtin.go

**Problem:**
Catalog with same template name can  not be imported.
**Solution:**
Add catalog name as prefix to its template.
#1854 #1363 #1340

fix: add catalog name to template

---

pkg/apis/resource/extension_view.go

https://github.com/seal-io/walrus/issues/1945

fix: missing res labels for matches on redeploy

---

pkg/resource/resource.go

**Problem:**
Production env resources do not show stop label. As https://github.com/seal-io/walrus/issues/1765#issuecomment-1899547756 introduced, production env should show stop label to users.
**Solution:**
Add stop label false in prod env.
https://github.com/seal-io/walrus/issues/1765#issuecomment-1899547756

fix: show stop label in prod

---

pkg/k8s/local.go
pkg/server/init_configs.go
pkg/server/runner.go
pkg/servervars/vars.go
staging/utils/netx/ipv4.go
staging/utils/netx/ipv4_test.go

support Russian Dolls
**problem**
1. the embedded k3s IP conflicts with the on-host cluster
2. the nesting embedded k3s keeps using root cgroup, which causes launching to fail. 
**solution**
1. when it starts k3s, walrus tries to pick a proper subnet according to the host's subnet.
2. when it starts k3, walrus picks a proper cgroup.
**related**
#1972

fix: failed to start in k3s cluster

---

deploy/manifests/walrus-file.yaml

**Problem:**
Without profile configured, the configured ports cannot be viewed on the UI. And the ports will be removed when upgrade on UI.
**Solution:**
Fill in the default profile `run`.
https://github.com/seal-io/walrus/issues/1928#issuecomment-1900065799

fix: walrus file profile attribute

---

pkg/apis/resourcedefinition/extension_view.go

**Problem:**
Resource definition detail page's watch request not working.
**Solution:**
Set `runtime.RequestUnidiStream`.
#1965

fix: resource definition detail page not updated

---

pkg/apis/template/extension.go
pkg/apis/templateversion/basic.go
pkg/dao/expose.go

**Problem:**
Now will expose server-generated schema while ui schema doesn't include components/variables
**Solution:**
return ui schema even it without components/variables
#1618

fix: return ui schema even it without components/variables

---

pkg/resource/computed_attributes.go
pkg/templates/schema_default.go

**Problem:**
While user input is different from default, computed attributes use default to calculate now.
**Solution:**
While user input is different from default, use user input attributes to generate computed attributes.
#1938

fix: support compute attributes base on user input

---

pkg/k8s/local.go
staging/utils/files/file.go

**problem**
failed to restart walrus with steps like `docker compose up -> docker compose down -> docker compose up`, the root cause is that the `compose down` has removed the docker network created by the first-time up. 
generally, if the outside networking changes, it affects the embedded Kubernetes cluster, and we cannot reset the joined node's PodCIDR at present.
**solution**
embedded Kubernetes cluster is for demonstration purposes, we never guarantee using it for production. so we can easily remove the Etcd data(similar to removing the node from a Kubernetes cluster) if the networking changes.
**related**
#1991  
@gitlawr, we need a WARNING at docs to tell users that it's dangerous to run workloads in the default-local environment.

fix: failed to restart after infra network changed

---

pkg/apis/runtime/router.go
pkg/cli/api/operation.go

**Problem:**
API get template by name doesn't work while template name include slash like (${catalog_name}/${template_name}
**Solution:**
enable UseRawPath to support getting path parameters from rawPath
#1997

fix: API get template by name doesn't work while template name include slash

---

pkg/cli/local/install.go

Change local walrus tag from `fmt.Sprintf("%s (%s)", Version, GitCommit)` to `Version`
https://github.com/seal-io/walrus/issues/2018

fix: use clean tag version for local walrus

---

pkg/templates/constraint.go

**Problem:**
Can not import template with out file schema.yaml. Walrus version constrain failed.
**Solution:**
Skip version constrain if there is not file shcema.
#2020

fix: check template constrain failed

---

pkg/cli/api/openapi.go
pkg/cli/cmd/local.go

**Problem:**
local install returns
```
runtime error: invalid memory address or nil pointer dereference
```
https://github.com/seal-io/walrus/issues/2018

fix: ready check fail after local install

---

pkg/apis/resourcerevision/extension.go
pkg/dao/resource_component.go
pkg/dao/resource_component_relationship.go

**Problem:**
Updating resource components relationships can lead to the violation of foreign key constraints. This issue arises during the update of resource components (see https://github.com/seal-io/walrus/blob/main/pkg/apis/resourcerevision/extension.go#L200). In the update process, old resources get deleted. However, if a relationship was created using a resource prior to its deletion, it can result in a query failure.
**Solution:**
Clear removed resource components before create components relationships.
#2049

fix: components relationship update failed

---

pkg/templates/openapi/default.go
pkg/templates/openapi/default_test.go
pkg/templates/openapi/testdata/empty/with_attributes_expected.json
pkg/templates/openapi/testdata/empty/with_attributes_input.json
pkg/templates/openapi/testdata/list/with_attributes_expected.json
pkg/templates/openapi/testdata/list/with_attributes_input.json
pkg/templates/openapi/testdata/list/with_attributes_input_default.json
pkg/templates/openapi/testdata/map/with_attributes_expected.json
pkg/templates/openapi/testdata/map/with_attributes_input.json
pkg/templates/openapi/testdata/map/with_attributes_input_default.json
pkg/templates/openapi/testdata/object/main.tf
pkg/templates/openapi/testdata/object/with_attributes_expected.json
pkg/templates/openapi/testdata/object/with_attributes_input.json
pkg/templates/openapi/testdata/object/with_attributes_input_default.json
pkg/templates/openapi/testdata/simple/with_attributes_expected.json
pkg/templates/openapi/testdata/simple/with_attributes_input.json
pkg/templates/openapi/testdata/simple/with_attributes_input_default.json

**Problem:**
Use user input attributes while exist, compare with merge it with ops configuration, merge is more intuitive. 
**Solution:**
After discussion, it was decided that the merge operation would eventually be performed, and the mutually exclusive parts of the merge would need to be handled in the template.
#2076

refactor: update generate schema default with attributes

---

pkg/cli/api/cache.go
pkg/cli/config/cache.go
pkg/cli/config/config.go

the original path processing uses the `path` package, which is for URL purpose, let's change to `filepath` package.
https://github.com/seal-io/walrus/issues/2069#issuecomment-1920667135

refactor: support windows file path

---

cmd/cli/main.go
pkg/cli/api/operation.go
pkg/cli/common/http_status.go
pkg/cli/config/config.go
pkg/cli/formatter/table.go
pkg/cli/manifest/request.go

**Problem:**
CLI context configured with the deleted project will cause validation failure while generating resource commands. 
**Solution:**
Should not check CLI context while generating resource commands
#2063

fix: should not check cli context while load cli command

---

.github/workflows/ci.yml

**Problem:**
run out of disk space in CI.
**Solution:**
Remove unused tools in the hosted runner. It reclaims ~10Gi disk space.
Before:
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   53G   21G  73% /
After:
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   43G   30G  60% /
**Related Discussions**
For more context:
https://github.com/actions/runner-images/issues/2875
https://github.com/orgs/community/discussions/26351

ci: more runner disk space

---

pkg/apis/resource/helper.go
pkg/apis/resource/helper_test.go

This is a further repair for the variable replacement, as missing the quotation marks for the var key in #2121.
The key should be `"${var.abc}"` rather than `${var.abc}`
#2117

fix: replace variables error

---

pkg/dao/workflow.go
pkg/dao/workflow_test.go
pkg/workflow/step/service_step.go

**Problem:**
- Can not reference workflow variables with hyphen
- When update create or update resource in step error occurs, workflow step will not show curl error.
**Solution:**
- support hyphen in workflow, as we adjust variables name rules in 0.5.0
- show more info in workflow service step. As the upgrade API of resource will not return any information, we may change it in the future with K8s API.
**Related Issue:** 
#2126  #1982

fix: workflow variables and logs

---

pkg/cli/api/cache.go
pkg/cli/api/openapi.go
pkg/cli/api/version.go
pkg/cli/cmd/version.go

**Problem:**
1. isDev info is useless, version is enough.
2. Now it won't return the client version while it can't get the server version.
**Solution:**
1. Removed isDev info.
2. Still return cli version, while the server isn't reachable.
#2073

refactor: enhance cli version command

---

pkg/cli/formatter/json.go

**Problem:**
cli json format use \t may missing indent  
**Solution:**
replace \t with blank space
#1531

refactor: enhance cli json format

---

pkg/cli/formatter/json.go
staging/utils/json/jsoniter.go

**Problem:**
json-iterator's MarshalIndent only only indent the first level. While generating cli from ci, it will force to use json-iterator, which will cause wrong indent.
https://github.com/json-iterator/go/issues/564
https://github.com/json-iterator/go/issues/645
**Solution:**
Update to use default encoding/json now, will update to json-iterator after bugs get fixed.
#1531

refactor: use encoding/json while generate cli output

---

pkg/apis/resource/extension.go

**Problem:**
server crash when get output for draft resource 
**Solution:**
Skip decoding output when isn't existed
#2152

fix: server crash when get output for draft resource

---

pkg/apis/subject/basic.go

**Problem:**
Searching users with keywords `n` returns all records, because `n` is in the value `builtin` of the domain field.
**Solution:**
Remove the domain field from the query fields.
#2024

fix: search users with name unexpected result

---

pkg/apis/environment/basic.go
pkg/apis/environment/extension.go
pkg/apis/resource/basic.go
pkg/apis/resource/extension.go
pkg/apis/resourcedefinition/extension.go
pkg/apis/resourcedefinition/handler.go
pkg/apis/setup.go
pkg/resourceruns/operation.go
pkg/resources/operation.go
pkg/scheduler/resource/relationship_check_task.go

**Problem:**
- draft resource does not have state record will cause panic when start or upgrade.
- progress task will mark incorrect resource state to deploying.
- rollback preview does not take effect
**Solution:**
- create resource state for draft resource
- remove resource state transitioning as run will handle resource state update.
- fix preview for rollback
#2175 #2172 #2167

fix: preview draft state

---

pkg/operator/k8s/kube/pod.go
pkg/operator/k8s/operator_get_keys.go

**Problem:**
The init container is returned before the run container when getting keys, which makes the init container the default one in the logs view.
**Solution:**
Sort the containers by their types in the order run<init<ephemeral to show the run container at first.
#1611

feat: view logs from the run container before the init container

---

pkg/apis/resourcerun/basic.go
pkg/resourceruns/status/status.go

**Problem:**
- A continuous fix for #2195, as dependant query get wrong resources.  https://github.com/seal-io/walrus/issues/2155#issuecomment-1980916339
- Remove useless resource information for resource run list API
- Remove inactive check
**Solution:**
Correct query of dependant query.
#2196 #2195

fix: dependency stop resource query wrong

---

pkg/apis/dashboard/extension.go
pkg/apis/dashboard/extension_view.go
pkg/dao/types/status/status_resourcerun.go

**Problem:**
Planning, Planned, Canceled, and Pending statuses are not included in the dashboard statistics.
**Solution:**
Ignore plan runs and keep only succeed, running, and failed statuses in Deployments to be consistent with statistics.
#2198

fix: dashboard lacks statistics for some status

---

pkg/operator/google/resourcestatus/redis_instance.go

**Problem:**
The name of the Google Redis instance is already the full identifier, so no need to prepend the extra path.
**Solution:**
Use the name directly to retrieve the Redis instance status.
#2204

fix: failed to get google redis instance status

---

pkg/terraform/parser/parser.go

**Problem:**
Google provider returns URL-encoded representation of google_service_networking_connection name in terraform state, which causes "%2F" to be displayed on walrus UI.
**Solution:**
Decode the instance ID to avoid incorrect format from the provider.
#2205

fix: google_service_networking_connection name format

---

pkg/dao/types/status/converter.go
pkg/dao/types/status/converter_test.go
pkg/dao/types/status/status.go
pkg/dao/types/status/status_resourcerun.go
pkg/deployer/terraform/deployer.go
pkg/operator/alibaba/resourcestatus/converter.go
pkg/operator/aws/resourcestatus/converter.go
pkg/operator/azure/resourcestatus/converter.go
pkg/operator/google/resourcestatus/converter.go
pkg/resourceruns/job/job.go
pkg/resourceruns/job/syncer.go
pkg/resourceruns/status/status.go

**Problem:**
As the status and color is not clear in walrus. We need introduce a new color to represent a `break point` status.
We make following status color desision, after this PR merged.
| Stage        | Color  |
| ------------ | ------ |
| Transitioning| Blue   |
| Inactive     | Gray   |
| Warning      | Yellow |
| Succeed      | Green  |
| Failed       | Red    |
@hibig UI need to be modified synchronously. Be careful with the color changed. Warning represents pause status.

feat: introduce new warning status summary

---

pkg/apis/resource/basic.go
pkg/apis/resource/extension.go
pkg/apis/resource/extension_view.go
pkg/apis/resourcerun/basic.go
pkg/resourceruns/job/syncer.go
pkg/resourceruns/status/status.go

**Problem:**
- When resource upgrade succeed but run job failed, it should not return error in Upgrade API, users should check logs in runs. https://github.com/seal-io/walrus/issues/1003#issuecomment-1987511659
- Add some debug information in resource run syncer.
**Solution:**
- Skip upgrade error when run created for resource upgrade.
- Print debug log for tracing status issues. #2216
#1003

fix: upgrade resource and run created with error

---

pkg/templates/loader/terraform_loader.go

**Problem:**
Load tags without terraform configuration files
**Solution:**
Skip load tags without terraform configuration files
#2222

fix: skip load tags without terraform configuration files

---

go.mod
pkg/apis/resourcerun/basic.go
pkg/deployer/terraform/command.go
pkg/server/runner.go
pkg/storage/config.go
pkg/storage/config_test.go
pkg/storage/s3.go

- provide region query for s3 config
- skip s3 bucket already created error
**Problem:**
- when do multi deployment runs, jobs will check and create bucket for the s3 service. But once one of them create the bucket successfully, the other try to create the same bucket will return already create error, we should ignore the error.
- region of s3 is not configurable, using the default `ap-north-1` as the region
- when plan set failed, the job still runs as success
**Solution:**
- ignore the `bucket already exit err`
- support config s3 region
- add curl params `--fail-with-body` to show error and exit when http response code is greater than 400, https://curl.se/docs/manpage.html
#2202

fix: show s3 bucket already owned error

---

pkg/apis/runtime/scheme_route_extension.go

**Problem:**
API `GET/POST /v1/projects/{project}/environments/{environment}/resources/{resource}/runs/{resourcerun}/plan` are used for deployer
**Solution:**
Skip generate cli command for these API
https://github.com/seal-io/docs/issues/205

chore: skip generate cli command to deployer used api
