seal-io/walrus

- pkg/dao/entx/extension/view/template/ent.tmpl
- pkg/dao/model/catalog_view.go
- pkg/dao/model/connector_view.go
- pkg/dao/model/environment_view.go
- pkg/dao/model/perspective_view.go
- pkg/dao/model/project_view.go
- pkg/dao/model/service_view.go
- pkg/dao/model/serviceresourcerelationship_view.go
- pkg/dao/model/setting_view.go
- pkg/dao/model/template_view.go
- pkg/dao/model/templateversion_view.go
- pkg/dao/model/variable_view.go
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
**Problem:**
Failed to gain the index fields from the *UpdateInput's `Model` function.
**Solution:**
Adjust entx generation template to value the index fields during *UpdateInput's `Model` function.
PR https://github.com/seal-io/walrus/pull/1175 addresses #1172, but it exposes the problem that this PR described. I prefer to make this PR a further fix for #1172 .
> fix: lose index fields after update input modeling

- deploy/manifests/kubernetes.yaml
- pkg/apis/logger.go
- pkg/apis/server.go
- pkg/kms/driver_k8s.go
**Problem:**
1. Log too many useless EOF when deployed behind AWS ELB.
2. Cannot finish the ACME after changing domain name.
3. Cannot finish the ACME with the default Kubernetes deployment.
**Solution:**
1. Discard the HTTP error log with the EOF suffix.
2. Introduce a Group concept to KMS service, different groups can own the key with same name.
3. Donot redirect the Kubelet probe request from 80 to 443.
#1168 #1174  #1173
> fix: cert generated

- go.mod
- go.sum
- pkg/catalog/builtin.go
- pkg/catalog/catalog.go
- pkg/catalog/catalog_test.go
- pkg/vcs/client.go
- pkg/vcs/driver/github/github.go
- pkg/vcs/driver/gitlab/gitlab.go
- pkg/vcs/driver/helper.go
- pkg/vcs/options/options.go
- pkg/vcs/repo.go
- pkg/vcs/transport/transport.go
- staging/utils/version/version.go
IMPORTANT: Please do not create a Pull Request without creating an issue first.
Problem:
Add builtin catalog server and record telemetry
Solution:
Support fetch git repositories from catalog server
Related Issue:
> feat: update builtin catalog server

- pkg/apis/service/basic_view.go
- pkg/apis/service/extension_view.go
- pkg/deployer/terraform/deployer.go
- pkg/deployer/terraform/parse.go
**IMPORTANT: Please do not create a Pull Request without creating an issue first.**
**Problem:**
Create a service that references a variable that does not exist, request return failed, but the service is created.
**Solution:**
Validate variables before handling request.
**Related  #Issue:**
https://github.com/seal-io/walrus/issues/1003
> fix: create serivce with nonexistent variables

- pkg/cron/locker.go
- pkg/cron/registry.go
- staging/utils/cron/cron.go
**Problem:**
The original renew loop may not quit after the holder changes.
**Solution:**
- If the holder is not me, quit the loop.
- Adjust the log to print the same style text of cron job.
#1201
> refactor: cron locker

- pkg/catalog/catalog.go
- pkg/scheduler/catalog/template_sync_task.go
**Problem:**
Catalog status stuck in Initializing state after executing CatalogTemplateSync task, missing status update.
**Solution:**
update catalog in CatalogTemplateSync task
#1233
> fix: catalog sync stuck status

- pkg/operator/k8s/kubeendpoint/endpoints.go
**Problem:**
ingress without host/ip will return an empty endpoint
**Solution:**
#1151
> fix: ignore empty ingress endpoints

- pkg/costs/deployer/cost_tools.go
- pkg/costs/deployer/default.go
- pkg/costs/deployer/deployer.go
- pkg/costs/deployer/helm.go
**Problem:**
Now we need prometheus charts and need to get chart dir, cost image from the environment, which makes it inconvenient in the dev environment
**Solution:**
Support download prometheus charts while it isn't existed, and add default value to make the cost tools
#1185
> refactor: add default value for cost tools

- pkg/service/service.go
**Problem:**
PR https://github.com/seal-io/walrus/pull/1187  only add variable validtion before reqeust handing.
Now creating service with a invalid service output still fail.
**Solution:**
Run all deployer task background. 
User could get response immediately after service creating. The failure with service outputs will be recorded into service revision.
https://github.com/seal-io/walrus/issues/1003
> fix: creating a service that references a service output that does not exist

- pkg/apis/template/extension.go
**Problem:**
Template versions with same `create_time` is ordered randomly instead of by version number.
**Solution:**
- Add `version` number as a subsequent column in default sorting.
- Convert the `version` strings into int arrays to avoid string sorting problem like v0.0.10 sorted before v0.0.2.
- Remove the customized sorting params, since it only allowed `version` field anyway.
#1267
> fix: template versions sometimes incorrect order

- pkg/apis/servicerevision/extension.go
**Problem:**
When deploying services fails for the first time(e.g. Fail to create VPC), the instance of some resources are empty. Upgrading the service does not cause the instance field updated.
**Solution:**
When getting a new service revision, in addition to resource creation and deletion, update the instance Edge for the existing resources as well.
#1283
> fix: service resources not updated when redeploying

- pkg/server/init_rbac.go
**Problem:**
Add permissions of catalogs and templates under projects.
**Solution:**
Modify catalogs and templates rbac of project view/member/owner.
#1325
> feat: add project scope catalogs/templates rbac

- pkg/apis/environment/basic.go
- pkg/apis/environment/basic_view.go
- pkg/dao/types/status/status.go
**Problem:**
need to show resource/service status in the environment list
#964
> feat: add resource status summary for environment

- cmd/cli/command.go
- cmd/cli/init.go
- pkg/cli/api/operation.go
- pkg/server/runner.go
- staging/utils/runtimex/runtime.go
**Problem:**
CLI shows useless logs.
**Solution:**
Remove CLI useless logs
#1015 
https://github.com/seal-io/walrus/issues/1405
> fix: remove cli useless logs

- pkg/apis/environment/basic.go
**Problem:**
Incorrect environment service/resource status statistics
**Solution:**
select resources when query env list
#1448
> fix: env resource summary count

- .golangci.yaml
- pkg/apis/environment/basic.go
- pkg/apis/environment/common.go
- pkg/apis/environment/extension.go
- pkg/apis/environment/extension_view.go
- pkg/apis/resource/basic.go
- pkg/apis/resource/basic_view.go
- pkg/apis/resource/extension.go
- pkg/apis/resource/extension_view.go
- pkg/apis/resourcerevision/extension.go
- pkg/apis/runtime/scheme_route_test.go
- pkg/dao/types/built_in_labels.go
- pkg/dao/types/status/status_resource.go
- pkg/dao/types/status/walker.go
- pkg/deployer/terraform/syncer.go
- pkg/resource/resource.go
- pkg/scheduler/resourcecomponent/status_sync_task.go
https://github.com/seal-io/walrus/issues/1316
> Support resource draft, stop and start

- pkg/cli/schema/format.go
- pkg/deployer/terraform/deployer.go
- pkg/templates/constraint.go
- pkg/templates/loader/terraform_loader.go
- pkg/templates/loader/terraform_loader_test.go
- pkg/templates/loader/testdata/full_schema/schema.yaml
- pkg/templates/openapi/ext.go
- pkg/templates/openapi/operation.go
- pkg/templates/translator/terraform_translator.go
- pkg/templates/translator/translator.go
- pkg/terraform/parser/parser.go
**Problem:**
Need to add order and span for better UI render
**Solution:**
Support  ui extension configure order and colSpan
#1306
> refactor: support generate span and order in schema

- go.mod
- pkg/apis/workflow/basic.go
- pkg/apis/workflowexecution/basic_view.go
- pkg/apis/workflowexecution/extension.go
- pkg/apis/workflowexecution/extension_view.go
- pkg/apis/workflowstepexecution/extension.go
- pkg/workflow/client.go
- pkg/workflow/reconcile.go
- pkg/workflow/status.go
- pkg/workflow/step/service_step.go
- pkg/workflow/template.go
**Problem:**
- can not reject for rerun executions (Reason: previous workflow resource not clean, the rerun workflow name changed due to conflict)
- deleting running workflow and executions
**Solution:**
- Clean workflow execution resource before rerun the workflow execution.
- add validation for deleting workflow and executions
#1429 #1430
> fix: reject approve failed and add validation

- pkg/apis/resource/extension.go
- pkg/terraform/parser/parser.go
**Problem:**
Tuple endpoint returns an invalid error
**Solution:**
Should not return invalid error while 
> fix: tuple endpoint return invalid error

- pkg/vcs/repo.go
**Problem:**
Skip importing archived templates.
**Solution:**
When adding a catalog, skip archived repositories.
#1484
> feat: skip importing archived templates

- pkg/apis/resource/extension.go
Fix the problem that templateID of resource using definition is set on rollback.
https://github.com/seal-io/walrus/issues/1474
> fix: rollback resource

- pkg/terraform/config/config.go
- pkg/terraform/config/config_test.go
**Problem:**
The reference of resource outputs is set to string when generate terraform configs
Failed to reference a complex type variable #1488
**Solution:**
keep the output variable type when generate the config
#1488
> fix(terraform): failed to reference a complex type variable

- pkg/apis/resource/extension.go
- pkg/templates/loader/terraform_loader_test.go
- pkg/templates/translator/terraform_translator.go
**Problem:**
Update schema for tuple
#1493
> fix: update tuple schema

- pkg/apis/environment/basic_view.go
- pkg/apis/environment/extension.go
- pkg/apis/environment/extension_view.go
- pkg/apis/resource/extension.go
- pkg/apis/resource/extension_view.go
- pkg/dao/resource_relationship.go
- pkg/dao/types/status/status.go
- pkg/dao/types/status/status_resource.go
- pkg/resource/resource.go
- pkg/scheduler/resource/relationship_check_task.go
This PR address multiple issues:
1. Support updaing draft(https://github.com/seal-io/walrus/issues/1462, https://github.com/seal-io/walrus/issues/1461)
2. Add inactive resource count to env list API(https://github.com/seal-io/walrus/issues/1469). This is a temporary fix before https://github.com/seal-io/walrus/issues/1500 is addressed.
3. Fix scheduling resources to be stopped.(https://github.com/seal-io/walrus/issues/1491)
See commit message for details.
> multiple fixes

- .github/workflows/ci.yml
**Problem:**
Latest sometimes means the latest stable release, while our latest is the dev branch, the latest release is confused.
**Solution:**
Remove the latest release.
#1486
> refactor: only release cli for tag

- .github/workflows/ci.yml
**Solution:**
Release the latest CLI to oss
#1486
> refactor: release latest cli to oss

- hack/mirror/full_image_list.txt
- hack/mirror/mirror_image_list.txt
- pkg/server/init_workflow_runtime.go
- pkg/settings/settings.go
- pkg/workflow/deployer/default.go
- pkg/workflow/step/service_step.go
**Problem:**
**Solution:**
Support mirror workflow images, modify step images, support image repository for workflows.
#412
> feat: mirror workflow images

- pkg/apis/environment/common.go
- pkg/apis/resource/basic_view.go
- pkg/apis/resource/extension_view.go
**Problem:**
validate the resource variables with the original schema but not the (customized) UI schema.
**Solution:**
prioritize using UI schema verification if found.
partial fix for https://github.com/seal-io/walrus/issues/1492
> fix: donot respect ui schema

- pkg/dao/types/schema.go
- pkg/templates/loader/terraform_loader.go
- pkg/templates/loader/terraform_loader_test.go
- pkg/templates/loader/testdata/any_variable/main.tf
- pkg/templates/translator/terraform_translator.go
- pkg/templates/translator/translator.go
**Problem:**
1. fix mismatch type and default value cause validate failed
2. add nullable to schema
#1519 
#1492
> fix: schema bugs add nullable to schema

- pkg/apis/workflow/extension.go
- pkg/apis/workflow/extension_view.go
Tidy up workflow run input.
Before:
After:
https://github.com/seal-io/walrus/issues/1535
> fix: update workflow run action

- pkg/templates/loader/terraform_loader.go
**Problem:**
groupOrder reset.
**Solution:**
Skip set groupOrder while exist
> refactor: skip set groupOrder while exist

- pkg/templates/loader/terraform_loader.go
**Problem:**
May generate the wrong group order
**Solution:**
fix generate group sequence
> fix: generate wrong group order

- pkg/templates/git.go
**Problem:**
template version missing subpath.
**Solution:**
add subpath for template version when import a template with subpath
#1579
> fix: template version mission subpath

- pkg/catalog/catalog.go
**Problem:**
Trim template's "terraform-" prefix.
#1586
> feat: trim "terraform-" template prefix

- pkg/dao/workflow.go
- pkg/dao/workflow_test.go
**Problem:**
Bug: Workflow params not set overwritable will make valid failed.
Reason: The input variable map is overwirte to request when validate.
**Solution:**
Aviod overwrite the raw variables when validate run workflow input.
#1560
> fix: cannot run workflow with non-configurable variable

- pack/server/image/Dockerfile
**Problem:**
In offline senario, some images may need to download will block walrus server start up.
**Solution:**
Add airgap images to walrus image.
#412
> feat: support airgap

- pkg/operator/k8s/kubestatus/walker.go
**Problem:**
Do not identify the completed condition of the Pod created by a Job.
**Solution:**
In the status walker, give two decisions to solve this case.
#1555
> fix: cannot identify completed kube job components

- .github/workflows/ci.yml
- hack/mirror/full_image_list.txt
**Problem:**
Missing airgap deployer image in list
**Solution:**
- Add airgap image to list.
- Release full image list in asset.
> fix: image list

- pkg/operator/k8s/kubestatus/status.go
**Problem:**
Since the progressing job has no conditions, Walrus reports a Server Error for it.
**Solution:**
Clarify the status of progressing job.
#1555
> refactor: correct progressing job's status

- pkg/resource/resource.go
**Problem:**
resource relationships are not kept when cloning draft.
https://github.com/seal-io/walrus/issues/1612
> fix: missing relationship on cloning draft

- pkg/apis/environment/basic.go
- pkg/apis/environment/basic_view.go
**Problem:**
Service/resource status on environment list page not updated automatically.
**Solution:**
Support watch api. Subscribe resource model change and push environment updates.
#1454
> feat: update service/resource status on environment list page

- go.mod
- pkg/apis/resourcedefinition/basic.go
- pkg/apis/resourcedefinition/helper.go
- pkg/apis/resourcedefinition/helper_test.go
- pkg/apis/resourcedefinition/testdata/irrelevant/expected.yaml
- pkg/apis/resourcedefinition/testdata/irrelevant/given.1.yaml
- pkg/apis/resourcedefinition/testdata/irrelevant/given.2.yaml
- pkg/apis/resourcedefinition/testdata/shrink/expected.yaml
- pkg/apis/resourcedefinition/testdata/shrink/given.1.yaml
- pkg/apis/resourcedefinition/testdata/shrink/given.2.yaml
- pkg/apis/resourcedefinition/testdata/similar/expected.yaml
- pkg/apis/resourcedefinition/testdata/similar/given.1.yaml
- pkg/apis/resourcedefinition/testdata/similar/given.2.yaml
- pkg/dao/types/schema.go
**Problem:**
- keep the keys have the same name, but do not consider the type.
- have not shrunk the range, including description, default, enum, maximum, minimum, and so on.
**Solution:**
shrink the first-level properties of the schemas.
#1603
> refactor: generate ui schema for res def

- pack/server/image/Dockerfile
**Problem:**
Git will create zombie process when sync template or catalog in poor network.
**Solution:**
Using [`tini`](https://github.com/krallin/tini) to manage zombie processes and signal forwarding.
#1622
> fix: zombie processes

- pack/server/image/Dockerfile
> revert: "fix: zombie processes"

- pkg/apis/resource/extension.go
- pkg/apis/resourcerevision/extension.go
- pkg/dao/resource_component.go
- pkg/resourcecomponents/state.go
**Problem:**
When user-defined endpoints exist, the endpoints from resources are ignored.
**Solution:**
Grab both user-defined endpoints and resources
#1641 
#1443
> refactor: return both user defined endpoints and endpoints from resource

- pkg/dao/types/schema.go
**Problem:**
Sometimes import catalog failed. Catalog contains invalid templates may not have schema.
**Solution:**
Template schema will be set to variables and outputs not exist.
#1693
> fix: import catalog failed

- pkg/templates/git.go
**Problem:**
Can not force refresh template or catalog template version with tag updated.
**Solution:**
Make update template version as default behavior. If user hard reset tag, it will update template version.
#1597
> feat: support force reset template versions

- pkg/apis/environment/basic.go
- pkg/apis/environment/common.go
- pkg/apis/environment/extension.go
- pkg/apis/resource/basic.go
- pkg/apis/resource/extension.go
- pkg/deployer/terraform/deployer.go
- pkg/deployer/types/new.go
- pkg/deployer/types/types.go
- pkg/resource/resource.go
- pkg/scheduler/resource/relationship_check_task.go
**Problem:**
Resource is not deployed imediately on clone/batch creation.
**Solution:**
Support imediately deploy resource when resource does not have dependencies.
#1740
> feat: instant deploy resource without dependencies

- pkg/operator/k8s/operator.go
**Problem:**
`PollUntilContextCancel` only returns timeout error after retrying till context deadline exceeded.
**Solution:**
Record the last error and return it if not succeeded.
#1347
> feat: Display specific error when adding Kubernetes connector fails

- pkg/dao/environment.go
Add system labels for environments related to connectors to support resource definition matching rules.
#1757
> feat: add system labels for environments related to connectors

- .github/workflows/ci.yml
- .github/workflows/clean.yml
- .github/workflows/mirror_images.yml
> ci: bump version

- pkg/apis/resource/extension_view.go
**Problem:**
Reuse Attribute validation failed for upgrade API
**Solution:**
Fill input with select resource for validation.
> fix: batch operation validation failed

- cmd/cli/command.go
- go.mod
- pkg/cli/cmd/local.go
- pkg/cli/config/config.go
- pkg/cli/local/check.go
- pkg/cli/local/install.go
- pkg/cli/local/uninstall.go
- pkg/dao/types/connector.go
- pkg/deployer/terraform/deployer.go
- pkg/deployer/terraform/jobctrl.go
- pkg/operator/docker/operator.go
- pkg/operator/docker/resourcestatus/docker_container.go
- pkg/operator/docker/resourcestatus/status.go
- pkg/operator/k8s/intercept/tf_types.go
- pkg/operator/registry.go
- pkg/server/init_casdoor.go
- pkg/server/init_local_environment.go
- pkg/settings/settings.go
- pkg/terraform/convertor/convert.go
- pkg/terraform/convertor/docker.go
1. Support docker in local environment mode.
2. Add docker operator implementation
3. Support cli install/unistall local walrus
Examples:
```
$ walrus local install
$ walrus local uninstall
```
Related issue: https://github.com/seal-io/walrus/issues/1710
> feat: add local docker mode

- pkg/cli/schema/format.go
- pkg/cli/schema/generate.go
- pkg/cli/schema/generate_test.go
- pkg/cli/schema/testdata/simple/expected.yaml
- pkg/cli/schema/testdata/simple/main.tf
- pkg/cli/schema/testdata/simple/schema.yaml
- pkg/cli/schema/testdata/with_context/expected.yaml
- pkg/cli/schema/testdata/with_context/main.tf
- pkg/cli/schema/testdata/with_context/schema.yaml
**Problem:**
After this [PR](https://github.com/seal-io/walrus/pull/1739) generating schema for variables including context will cause panic. 
**Solution:**
Fix panic.
#1788
> fix: fix remove context cause panic

- pkg/apis/connector/basic_view.go
**Problem:**
Can not add new k8s connector
**Solution:**
Pass in the model Client when validating. 
#1801
> fix: add connector validate failed

- pack/server/image/Dockerfile
- pkg/deployer/installer/hermitcrab/installer.go
- support opentofu registry
- expose metrics
See https://github.com/seal-io/hermitcrab/commits/main/?since=2023-12-30&until=2024-01-03
https://github.com/seal-io/walrus/issues/1809
> refactor(hermitcrab): bump version

- pkg/apis/catalog/basic_view.go
**Problem:**
Can not create gitee type catalog.
**Solution:**
Fix validation.
#1756
> fix: catalog validation failed

- pkg/resource/resource.go
create resource panic when resource label is nil
> fix: nil resource label condition

- pkg/templates/loader/terraform_loader.go
- pkg/templates/loader/terraform_loader_test.go
- pkg/templates/loader/testdata/any_variable/expected.yaml
- pkg/templates/loader/testdata/complex_default/expected.yaml
- pkg/templates/loader/testdata/complex_default/main.tf
- pkg/templates/loader/testdata/complex_variable/expected.yaml
- pkg/templates/loader/testdata/with_description/expected.yaml
- pkg/templates/loader/testdata/with_only_default/expected.yaml
- pkg/templates/loader/testdata/with_variable/expected.yaml
- pkg/templates/translator/terraform_translator.go
- pkg/templates/translator/translator.go
**Problem:**
1. missing default value in some case while generate schema
2. nullable cause UI validate error
**Solution:**
1. Fix the default value generated
2. remove nullable
#1356 
#1688
> refactor: nullable and default in schema generate

- pkg/apis/dashboard/extension.go
- pkg/apis/dashboard/extension_view.go
- pkg/apis/environment/common.go
- pkg/apis/environment/extension.go
- pkg/apis/resource/basic.go
- pkg/apis/resource/basic_view.go
- pkg/apis/resource/extension.go
- pkg/apis/resourcerevision/extension.go
- pkg/apis/template/basic.go
- pkg/apis/template/basic_view.go
- pkg/catalog/catalog.go
- pkg/cli/interpolation/interpolation.go
- pkg/cli/interpolation/interpolation_test.go
- pkg/dao/resource_component_relationship.go
- pkg/dao/resource_relationship.go
- pkg/dao/types/graph.go
- pkg/deployer/terraform/deployer.go
- pkg/deployer/terraform/parse.go
- pkg/deployer/terraform/parse_test.go
- pkg/resource/resource.go
- pkg/scheduler/resource/relationship_check_task.go
- pkg/scheduler/resourcecomponent/status_sync_task.go
https://github.com/seal-io/walrus/issues/1770
> refactor: remove isService filter and svc expr substitution

- pkg/apis/resource/extension_view.go
**Problem:**
Comment parameter should be submitted in payload instead of query.
#1829
> fix: rollback revision comment param

- README.md
> docs: update readme [skip ci]

- pkg/apis/resource/basic.go
refactor: support sorting resource type
#1762
> refactor: support sorting resource type

- go.mod
- go.sum
**Problem:**
Implement retrieving topics from gitee.
#1852
> fix: retrieve repo topics from gitee

- pkg/apis/runtime/request_stream.go
fix(websocket): failed on terminal interaction
filter out the invalid utf8 runes
#1863
> fix(websocket): failed on terminal interaction

- pkg/apis/environment/common.go
- pkg/apis/resource/basic.go
- pkg/apis/resource/common.go
- pkg/apis/resource/extension.go
- pkg/resource/resource.go
**Problem:**
- wrong subject id for resource operation like upgrade, start, stop.
- clone resource missing default stop labels
**Solution:**
- update subject id for resources when user do resource operations.
- add misssing default labels for batch create API
#1869 #1870
> fix wrong subject id for resource operations

- pkg/apis/workflow/basic.go
- pkg/workflow/status.go
**Problem:**
- cancelled workflow have running condition status
- search workflow with name failed
**Solution:**
- reset cancel status if workflow is stopped.
- fix workflow search field
#1841 #1842
> fix: workflow cancel status and search failed

- pkg/server/init_rbac.go
**Problem:**
Redundant project workflow permissions for system/user
**Solution:**
- remove workflow rbacs
https://github.com/seal-io/walrus/issues/1730#issuecomment-1853686189
> fix: user center permissions list with workflow 

- pkg/dao/types/walrus_file.go
**Problem:**
The fields of resource in the exported Walrus file currently do not conform to common reading habits.
**Solution:**
Reorder the fields in the struct and unmarshall the bytes into MapSlice directly to keep the order from struct.
#1781
> feat: optimize fields order in Walrus file

- pkg/apis/resource/helper.go
**Problem:**
Not enough SQL query parameters were provided.
**Solution:**
Refill `ResourceDefinitionMatchingRuleID`.
#1910
> fix: failed on resource import deploying

- pkg/resource/computed_attributes.go
**Problem:**
apply walrus file cause panic
**Solution:**
fix wrong precheck
#1910
> fix: resource id check cause panic

- hack/mirror/walrus-images.txt
- pack/server/image/Dockerfile
feat: embed opentofu deployer
#1879
> feat: embed opentofu deployer

- pkg/resourcedefinitions/helper.go
**problem**
this happens when the rules are configured with the same template but have different defaults.
since we take the defaults from a map indexed by the template ID before, we only get one default value at processing.
**solution**
getting defaults from the original matching rules.
**related**
#1946
> fix: invalid defaults in res def

- deploy/manifests/docker-compose.yaml
- deploy/manifests/walrus-file.yaml
**Problem:**
Provide a walrus file for walrus.
#1928
> feat: walrus file for walrus

- pkg/cli/api/version.go
**Problem:**
Wrong  cli and server version compatibility detect info
**Solution:**
Update to correct info
#1959
> fix: update cli and server version compatibility detect info

- pkg/apis/resource/extension_view.go
- pkg/workflow/status.go
- pkg/workflow/template.go
**Problem:**
- can not upgrade resource in workflow
- a pending step will not change status when cancelling workflow.
- workflow execution status will not changed to error when sub step failed.
**Solution:**
- add resource definition matching rules for resource step.
- omitted step will update step status
- fail workflow fast when step failed
#1955 #1956 #1957
> fix: workflow status update and resource step can not upgrade 

- pkg/apis/resource/basic_view.go
- pkg/apis/resource/extension_view.go
- pkg/apis/resource/helper.go
- pkg/dao/types/property/field.go
- pkg/deployer/terraform/deployer.go
- pkg/deployer/terraform/parse.go
- pkg/resource/dependency.go
- pkg/resource/interpolation.go
- pkg/variable/variable.go
**Problem:**
attributes include ${var.xx} or ${res.xx.output} may failed to validate
**Solution:**
inject attributes before validating with schema
#1931
> refactor: inject var.xx and res.xx.output attribute before validate

- pkg/workflow/template.go
**Problem:**
Step with retry strategy status not update when failed.
**Solution:**
Should not fail fast for step template.
#1984
> fix: retry failed status not updated

- pkg/resourcedefinitions/helper.go
**Problem:**
The generated UI schema doesn't process the immutable attribute.
**Solution:**
Merge immutable attributes in schema.
#1970
> fix: merge immutable attributes in schema

- pkg/dao/types/property/field.go
**Problem:**
Validate any type with schema may causes deploy fail
**Solution:**
Skip validate any type with schema
#2001
> refactor: skip validate for any type attributes

- pkg/cli/api/openapi.go
- pkg/cli/api/operation.go
- pkg/cli/api/version.go
- pkg/cli/cmd/context.go
- pkg/cli/cmd/local.go
- pkg/cli/cmd/login.go
- pkg/cli/cmd/prerun.go
- pkg/cli/config/cache.go
- pkg/cli/config/config.go
- pkg/cli/config/server_context.go
**Problem:**
1. cli wait for the tls handshake timeout while the remote server is unreachable
2. show version compare log while listing resource
**Solution:**
1. reduce the timeout by adding dial to check reachable, reduce the tls handshake timeout and remove duplicate validation multiple times
2. remove version compare while listing resource
3. remove env clone command
#1960 
#1959
> refactor: enhance cli

- pkg/cli/config/config.go
**Problem:**
Walrus local install return access failed
**Solution:**
Set reachable while check access
> fix: walrus local installed return access failed

- pkg/server/init_catalogs.go
- pkg/server/runner.go
> refactor: tidy up run options

- pkg/templates/openapi/default.go
**Problem:**
Crash while creating definition with template with schema doesn't include component
**Solution:**
Check schema empty before use it
#2023
> fix: crash after use template without components

- pkg/workflow/installer/argoworkflows/installer.go
**Problem:**
No need to interact with argo CD crds right now.
**Solution:**
Remove aggregate roles when install argo workflow chats.
> refactor(workflow): remove aggregate roles of argo workflow

- pkg/apis/resource/common.go
**Problem:**
Resource definition detail page manage resources across different environments, which results in duplicate resource names failing on name checks.
**Solution:**
Change name checking to ID checking.
#2032
> fix: resource definition batch resource operations fail for duplicate names

- pkg/apis/runtime/scheme_route_extension.go
**Problem:**
cli connector show cost-related commands.
**Solution:**
ignore cost commands
> refactor: remove connector cost command

- .github/workflows/ci.yml
**Problem:**
Add checksum for release assets.
#2057
> ci: add checksums for release assets

- .github/workflows/ci.yml
- hack/build.sh
- hack/lib/target.sh
- pkg/apis/cli/handler.go
- staging/utils/files/helper_windows.go
- staging/utils/signals/handler_posix.go
- staging/utils/signals/handler_windows.go
- staging/utils/signals/syscall_waitid_posix.go
refactor: support windows server build
**related**
#2069 
**TODO**
> refactor: support windows server build

- .github/workflows/ci.yml
- hack/mirror/walrus-images.txt
- hack/package.sh
**Problem:**
The walrus image tag in walrus-images.txt is still v0.4.0.
**Solution:**
Change to v0.5.0.
#2080
> fix: walrus image tag in walrus-images.txt

- .github/workflows/ci.yml
- hack/package.sh
for now, the package layout looks as shown, which causes two problems: 1. UI cannot download CLI as not found; 2. failed to upload CLI to Tencent COS.
make sure the package layout is as below:
- upload assets to COS  from `walrus/server/cos` dir.
- release assets to Github from `walrus/server/release` dir.
#2080
> fix: failed upload cli

- pkg/cli/schema/testdata/simple/expected.yaml
- pkg/cli/schema/testdata/simple/schema.yaml
- pkg/cli/schema/testdata/with_context/expected.yaml
- pkg/cli/schema/testdata/with_context/schema.yaml
- pkg/resourcedefinitions/helper.go
- pkg/resourcedefinitions/helper_test.go
- pkg/resourcedefinitions/testdata/align_schemas/irrelevant/expected.yaml
- pkg/resourcedefinitions/testdata/align_schemas/irrelevant/given.1.yaml
- pkg/resourcedefinitions/testdata/align_schemas/irrelevant/given.2.yaml
- pkg/resourcedefinitions/testdata/align_schemas/shrink/expected.yaml
- pkg/resourcedefinitions/testdata/align_schemas/shrink/given.1.yaml
- pkg/resourcedefinitions/testdata/align_schemas/shrink/given.2.yaml
- pkg/resourcedefinitions/testdata/align_schemas/similar/expected.yaml
- pkg/resourcedefinitions/testdata/align_schemas/similar/given.1.yaml
- pkg/resourcedefinitions/testdata/align_schemas/similar/given.2.yaml
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/mutually_exclusive/expected.yaml
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/mutually_exclusive/given.yaml
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/normal/expected.yaml
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/normal/given.yaml
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/default.1.json
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/default.2.json
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/expected.yaml
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/given.yaml
make optional on the array property if all default values are not the same.
https://github.com/seal-io/walrus/issues/2060#issuecomment-1921260126
https://github.com/seal-io/walrus/issues/2097
> fix: failed make optional on array property

- pkg/cli/cmd/local.go
- pkg/cli/local/install.go
- pkg/cli/local/options.go
Refer to https://github.com/seal-io/docs/pull/191/files for the UX.
https://github.com/seal-io/walrus/issues/2062
> feat: support configuring local walrus env

- pkg/cli/config/config.go
fix: failed load project/environment in cli
2100
> fix: failed load project/environment in cli

- pkg/resourcedefinitions/helper.go
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/default.1.json
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/default.2.json
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/expected.yaml
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/given.yaml
make optional on the map property if all default values are not the same.
https://github.com/seal-io/walrus/issues/2060#issuecomment-1923382504
https://github.com/seal-io/walrus/issues/2097
> fix: failed make optional on map property

- pkg/resourcedefinitions/helper.go
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/default.1.json
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/default.2.json
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/expected.yaml
- pkg/resourcedefinitions/testdata/refill_variable_schema_ref/optional/given.yaml
fix: failed keeping required if object has required properties
#https://github.com/seal-io/walrus/issues/2060#issuecomment-1923616151
#https://github.com/seal-io/walrus/issues/2109
> fix: failed keeping required if object has required properties

- pkg/apis/environment/common.go
- pkg/apis/resource/basic_view.go
- pkg/apis/resource/extension_view.go
- pkg/cli/local/install.go
https://github.com/seal-io/walrus/issues/2140
> Add restart policy for local walrus

- go.mod
- pkg/apis/templateversion/basic.go
- pkg/apis/templateversion/extension.go
- pkg/dao/types/schema.go
- pkg/templates/constraint.go
- pkg/templates/git.go
- pkg/templates/icon.go
- pkg/templates/openapi/default_test.go
- pkg/templates/schema.go
- pkg/templates/syncer.go
- pkg/vcs/repo.go
**Problem:**
UI schema will be reset after refreshing the template
**Solution:**
Prevent reset user edited UI schema while refreshing
#2045
> fix: template ui schema is reset after refreshed

- pkg/apis/resourcerun/extension.go
- pkg/resourceruns/operation.go
- pkg/resources/operation.go
- pkg/scheduler/resource/relationship_check_task.go
**Problem:**
- resource run status stuck when canceling.
- resource schedule failed run status will stuck.
**Solution:**
- fix resource run status stuck in canceling.
- fix resource scheduler failed run status not updated.
#2163
> fix: canceling status and dependency failed update

- deploy/manifests/docker-compose.yaml
- deploy/manifests/kubernetes.yaml
- docs/DEVELOPMENT.md
- hack/mirror/walrus-images.txt
- pkg/resourceruns/job/job.go
- pkg/resources/operation.go
**Problem:**
- stop non-components resource will delete it.
- HA deployment should update
**Solution:**
- only change status for resource without components
- update HA deployment files.
#2155
> fix: stop resource without components will delete resource

- pkg/cli/api/body_param.go
- pkg/cli/api/operation.go
- pkg/cli/manifest/request.go
**Problem:**
CLI calling API with value like {} may cause a validation issue. 
**Solution:**
Remove empty value before request.
#2178
> fix: remove empty field when cli post/update resource

- pack/server/image/Dockerfile
fix: failed start k3s coredns
see https://github.com/k3s-io/k3s/issues/9381
#2187
> fix: failed start k3s coredns

- deploy/manifests/docker-compose.yaml
- pkg/apis/environment/extension.go
- pkg/apis/resource/basic.go
- pkg/apis/resourcerun/basic_view.go
- pkg/cli/api/body_param.go
- pkg/cli/api/operation.go
- pkg/cli/cmd/apply.go
- pkg/cli/cmd/delete.go
- pkg/cli/cmd/prerun.go
- pkg/cli/formatter/formatter.go
- pkg/cli/formatter/table.go
- pkg/cli/manifest/object.go
- pkg/cli/manifest/operator.go
- pkg/cli/manifest/option.go
- pkg/cli/manifest/request.go
- pkg/cli/manifest/waiter.go
**Problem:**
1. Support preview and comment when cli apply walrus file
2. Import walrus file crash
3. This refactor commit https://github.com/seal-io/walrus/commit/41f4d981a16d1792596fae107ec91fbc9db6de3c causing the patch API to be lost unexpectedly
4. docker-compose lack of minio volume
#2181 
#2186
> feat: support preview and comment when cli apply walrus file

- pkg/resourceruns/status/status.go
- pkg/resources/operation.go
- pkg/scheduler/resource/relationship_check_task.go
**Problem:**
- validation status failed as request of resource does not pass status.
- modify dependency error message
- query stopping resource condition error
**Solution:**
- remove validation in operation upgrade
- update query conditon in  resource run dependant check
#1461 #2155
> fix: remove validation in operation, update message

- pkg/resourcedefinitions/builtin.go
**Problem:**
As the template version name doesn't consistently follow the format fmt.Sprintf("%s/%s-%s", catalog.BuiltinCatalog().Name, connectorType, resourceType), such as in cases like https://github.com/walrus-catalog/terraform-alicloud-rds-mysql, the generated name might encounter issues when attempting to query the template version.
**Solution:**
Use the templateID to query the template version.
#2213
> fix: errors occurred while creating the built-in resource definitions

- go.mod
- pkg/storage/s3.go
**Problem:**
- measuring ignore error condition failed, as the minio-go error is not match s3 sdk error
**Solution:**
- correct err condition, using code to identify the true error.
#2022
> fix: measure s3 ignore error failed

- pkg/scheduler/resourcecomponent/status_sync_task.go
**Problem:**
- resource sometimes will stuck in deploying. `Component status check` scheduler will select older resource that is in `deploying` status and overwrite status to db after the task finished.
**Solution:**
- query resource again and skip deploying status resource update in scheduler. As the scheduler may take a long time to complete. A better way is using CAS.
#2216
> fix: resource status stucking in deploying

- pkg/apis/environment/extension_view.go
- pkg/cli/cmd/context.go
- pkg/cli/cmd/login.go
- pkg/cli/config/config.go
- pkg/cli/config/server_context.go
**Problem:**
CLI use token and UI use API Key
**Solution:**
Rename token to API key
#2241
> refactor: cli update token to api key

- pkg/apis/resourcerun/basic.go
- pkg/deployer/terraform/jobctrl.go
- pkg/operator/k8s/kube/pod.go
- pkg/workflow/step/service_step.go
**Problem:**
- Workflow step shows no logs and return error.
- Resource run list stream doest not return record after succeeded. https://github.com/seal-io/walrus/issues/2192#issuecomment-1996902795
**Solution:**
- As the resource run has two stage, the workflow step needs update to fetch two step logs.
- Return plan and apply records.
#2249
> fix: workflow shows no logs

- pkg/apis/dashboard/extension.go
**Problem:**
- dashboard statistics number is not correct.
**Solution:**
- correct the statistics.
#2259
> fix: dashboard statistics wrong
